/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Zona
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        JDPEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMConsultas = new javax.swing.JMenu();
        JMIMesa = new javax.swing.JMenuItem();
        JMIProducto = new javax.swing.JMenuItem();
        JMIPedido = new javax.swing.JMenuItem();
        JMIPedidoProducto = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        JMCuenta = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        JMSalir = new javax.swing.JMenu();
        JMISalir = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        javax.swing.GroupLayout JDPEscritorioLayout = new javax.swing.GroupLayout(JDPEscritorio);
        JDPEscritorio.setLayout(JDPEscritorioLayout);
        JDPEscritorioLayout.setHorizontalGroup(
            JDPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        JDPEscritorioLayout.setVerticalGroup(
            JDPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        JMConsultas.setText("Consultas");
        JMConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMConsultasActionPerformed(evt);
            }
        });

        JMIMesa.setText("Mesa");
        JMIMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIMesaActionPerformed(evt);
            }
        });
        JMConsultas.add(JMIMesa);

        JMIProducto.setText("Producto");
        JMIProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIProductoActionPerformed(evt);
            }
        });
        JMConsultas.add(JMIProducto);

        JMIPedido.setText("Pedido");
        JMIPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIPedidoActionPerformed(evt);
            }
        });
        JMConsultas.add(JMIPedido);

        JMIPedidoProducto.setText("Pedido de un producto");
        JMIPedidoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIPedidoProductoActionPerformed(evt);
            }
        });
        JMConsultas.add(JMIPedidoProducto);

        jMenuItem2.setText("Consultas de Pedidos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        JMConsultas.add(jMenuItem2);

        jMenuBar1.add(JMConsultas);

        JMCuenta.setText("Cuenta");

        jMenuItem6.setText("TotalPagar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        JMCuenta.add(jMenuItem6);

        jMenuBar1.add(JMCuenta);

        JMSalir.setText("Salir");

        JMISalir.setText("Salir");
        JMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMISalirActionPerformed(evt);
            }
        });
        JMSalir.add(JMISalir);

        jMenuBar1.add(JMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDPEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDPEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMIMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIMesaActionPerformed
        JDPEscritorio.removeAll();
        JDPEscritorio.repaint();
        VentanaMesa ventanaMesa = new VentanaMesa();
        ventanaMesa.setVisible(true);
        JDPEscritorio.add(ventanaMesa);
        JDPEscritorio.moveToFront(ventanaMesa);
    }//GEN-LAST:event_JMIMesaActionPerformed

    private void JMConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMConsultasActionPerformed

    private void JMIProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIProductoActionPerformed
        JDPEscritorio.removeAll();
        JDPEscritorio.repaint();
        VentanaProducto ventanaProducto = new VentanaProducto();
        ventanaProducto.setVisible(true);
        JDPEscritorio.add(ventanaProducto);
        JDPEscritorio.moveToFront(ventanaProducto);
    }//GEN-LAST:event_JMIProductoActionPerformed

    private void JMIPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIPedidoActionPerformed
        JDPEscritorio.removeAll();
        JDPEscritorio.repaint();
        VentanaPedido ventanaPedido = new VentanaPedido();
        ventanaPedido.setVisible(true);
        JDPEscritorio.add(ventanaPedido);
        JDPEscritorio.moveToFront(ventanaPedido);
    }//GEN-LAST:event_JMIPedidoActionPerformed

    private void JMIPedidoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIPedidoProductoActionPerformed
        JDPEscritorio.removeAll();
        JDPEscritorio.repaint();
        VentanaPedidoProducto ventanaPedidoProducto = new VentanaPedidoProducto();
        ventanaPedidoProducto.setVisible(true);
        JDPEscritorio.add(ventanaPedidoProducto);
        JDPEscritorio.moveToFront(ventanaPedidoProducto);
    }//GEN-LAST:event_JMIPedidoProductoActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JDPEscritorio.removeAll();
        JDPEscritorio.repaint();
        VentanaCalculos ventanaCalculos = new VentanaCalculos();
        ventanaCalculos.setVisible(true);
        JDPEscritorio.add(ventanaCalculos);
        JDPEscritorio.moveToFront(ventanaCalculos);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void JMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMISalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMISalirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        JDPEscritorio.removeAll();
        JDPEscritorio.repaint();
        VentanaPedidos2 ventanaPedido2 = new VentanaPedidos2();
        ventanaPedido2.setVisible(true);
        JDPEscritorio.add(ventanaPedido2);
        JDPEscritorio.moveToFront(ventanaPedido2);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDPEscritorio;
    private javax.swing.JMenu JMConsultas;
    private javax.swing.JMenu JMCuenta;
    private javax.swing.JMenuItem JMIMesa;
    private javax.swing.JMenuItem JMIPedido;
    private javax.swing.JMenuItem JMIPedidoProducto;
    private javax.swing.JMenuItem JMIProducto;
    private javax.swing.JMenuItem JMISalir;
    private javax.swing.JMenu JMSalir;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
