/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AcessoADatos.PedidoData;
import Entidades.Pedido;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Zona
 */
public class VentanaPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaPedido
     */
    public VentanaPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.<>
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFIdPedido = new javax.swing.JTextField();
        jTfIdMesa = new javax.swing.JTextField();
        jTFNombreMesero = new javax.swing.JTextField();
        JTFImporte = new javax.swing.JTextField();
        JTFMinutos = new javax.swing.JTextField();
        JTFHoras = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JRBCobrada = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        JBSalir = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jBBuscarId = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JDCFecha = new com.toedter.calendar.JDateChooser();
        jBBuscarIdMesa = new javax.swing.JButton();
        jBBuscarNombreMesero = new javax.swing.JButton();
        jBBuscarFechaYHora = new javax.swing.JButton();
        jBBuscarImporte = new javax.swing.JButton();
        jBBuscarCobrada = new javax.swing.JButton();

        jLabel1.setText("PEDIDOS");

        jLabel2.setText("Id pedido");

        jLabel3.setText("Id mesa");

        jLabel4.setText("Nombre mesero");

        jLabel5.setText("Fecha");

        jLabel6.setText("Importe");

        jLabel7.setText("Hora");

        jLabel8.setText("Cobrada");

        jButton1.setText("Hacer pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        JBSalir.setText("Salir");
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });

        jBBuscarId.setText("Buscar ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBBuscarIdMesa.setText("Buscar ");

        jBBuscarNombreMesero.setText("Buscar ");

        jBBuscarFechaYHora.setText("Buscar ");

        jBBuscarImporte.setText("Buscar ");

        jBBuscarCobrada.setText("Buscar ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(68, 68, 68)
                                        .addComponent(jTFIdPedido))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(74, 74, 74)
                                        .addComponent(jTfIdMesa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(27, 27, 27)
                                        .addComponent(jTFNombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBBuscarIdMesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jBBuscarNombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addGap(216, 216, 216)
                                .addComponent(JBSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JTFHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JTFMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(JDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBBuscarFechaYHora)
                                        .addGap(15, 15, 15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JTFImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBBuscarImporte))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JRBCobrada)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jBBuscarCobrada)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscarId))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTfIdMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscarIdMesa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFNombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscarNombreMesero)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jBBuscarFechaYHora))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(JTFImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBBuscarImporte)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTFHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(JRBCobrada)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBBuscarCobrada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(JBSalir))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_JBSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pedido pedido = new Pedido();
        PedidoData pedidoData = new PedidoData();
        try{
            if(jTfIdMesa.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese el id de la mesa que desea agregar al pedido");
                return;
            }
            if(jTFNombreMesero.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese el nombre del mesero que desea agregar al pedido");
                return;
            }
            if(JDCFecha.getDate()==null){
                JOptionPane.showMessageDialog(this, "Ingrese la fecha que desea agregar al pedido");
                return;
            }
            if(Integer.parseInt(JTFHoras.getText())<0 || Integer.parseInt(JTFHoras.getText())>12 ){
                JOptionPane.showMessageDialog(this, "Ingrese una hora valida entre 0 y 12");
                return;                
            }
            if(Integer.parseInt(JTFMinutos.getText())<0 || Integer.parseInt(JTFMinutos.getText())>59 ){
                JOptionPane.showMessageDialog(this, "Ingrese una hora valida entre 0 y 59");
                return;                
            }
            if(JTFImporte.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese el Importe que desea agregar al pedido");
                return;
            }
            
            pedido.setIdMesa(Integer.parseInt(jTfIdMesa.getText()));
            pedido.setNombreMesero(jTFNombreMesero.getText());
            //combino fecha y hora 
            Instant instant = JDCFecha.getDate().toInstant();//
            LocalDate localDate = instant.atZone(ZoneId.systemDefault()).toLocalDate();
            String hora = JTFHoras.getText() + ":" + JTFMinutos.getText();//meto en un string la fecha y la hora
            LocalTime horaFinal = LocalTime.parse(hora, DateTimeFormatter.ofPattern("HH:mm"));
            LocalDateTime localDateTime = localDate.atTime(horaFinal);
            pedido.setFechaHora(localDateTime);
            pedido.setImporte(Double.parseDouble(JTFImporte.getText()));
            pedido.setCobrada(JRBCobrada.isSelected());
            pedidoData.agregarPedido(pedido);
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Solo debe ingresar números");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pedido pedido = new Pedido();
        PedidoData pedidoData = new PedidoData();
        try{
            if(jTFIdPedido.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese el id del pedido que desea modificar");
                return;
            }
                        
            if(jTfIdMesa.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese el id de la mesa a modificar");
                return;
            }
            if(jTFNombreMesero.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese el nombre del mesero a modificar");
                return;
            }
            if(JDCFecha.getDate()==null){
                JOptionPane.showMessageDialog(this, "Ingrese la fecha a modificar");
                return;
            }
            if(Integer.parseInt(JTFHoras.getText())<0 || Integer.parseInt(JTFHoras.getText())>12 ){
                JOptionPane.showMessageDialog(this, "Ingrese una hora valida entre 0 y 12");
                return;                
            }
            if(Integer.parseInt(JTFMinutos.getText())<0 || Integer.parseInt(JTFMinutos.getText())>59 ){
                JOptionPane.showMessageDialog(this, "Ingrese una hora valida entre 0 y 59");
                return;                
            }
            if(JTFImporte.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese el Importe a modificar");
                return;
            }
            
            pedido.setIdPedido(Integer.parseInt(jTFIdPedido.getText()));
            pedido.setIdMesa(Integer.parseInt(jTfIdMesa.getText()));
            pedido.setNombreMesero(jTFNombreMesero.getText());
            //combino fecha y hora 
            Instant instant = JDCFecha.getDate().toInstant();//
            LocalDate localDate = instant.atZone(ZoneId.systemDefault()).toLocalDate();
            String hora = JTFHoras.getText() + ":" + JTFMinutos.getText();//meto en un string la fecha y la hora
            LocalTime horaFinal = LocalTime.parse(hora, DateTimeFormatter.ofPattern("HH:mm"));
            LocalDateTime localDateTime = localDate.atTime(horaFinal);
            pedido.setFechaHora(localDateTime);
            pedido.setImporte(Double.parseDouble(JTFImporte.getText()));
            pedido.setCobrada(JRBCobrada.isSelected());
            pedidoData.modificarPedido(pedido);
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Solo debe ingresar números");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTFIdPedido.setText("");
        jTfIdMesa.setText("");
        jTFNombreMesero.setText("");
        JDCFecha.setDate(null);
        JTFHoras.setText("");
        JTFMinutos.setText("");
        JTFImporte.setText("");
        JRBCobrada.setSelected(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalir;
    private com.toedter.calendar.JDateChooser JDCFecha;
    private javax.swing.JRadioButton JRBCobrada;
    private javax.swing.JTextField JTFHoras;
    private javax.swing.JTextField JTFImporte;
    private javax.swing.JTextField JTFMinutos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jBBuscarCobrada;
    private javax.swing.JButton jBBuscarFechaYHora;
    private javax.swing.JButton jBBuscarId;
    private javax.swing.JButton jBBuscarIdMesa;
    private javax.swing.JButton jBBuscarImporte;
    private javax.swing.JButton jBBuscarNombreMesero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFIdPedido;
    private javax.swing.JTextField jTFNombreMesero;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTfIdMesa;
    // End of variables declaration//GEN-END:variables
}
